name: "Build & Test"

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test_decoder:
    name: Test Decoder
    runs-on: ubuntu-24.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgtest-dev cmake
          cd /usr/src/googletest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp lib/*.a /usr/lib

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and run unit tests
        run: |
          g++ -std=c++17 -Wall -Wextra -O2 test_decoder.cpp decoder.cpp -o test_decoder -lgtest -lgtest_main -lpthread
          ./test_decoder

      - name: Build decoder
        run: |
          g++ -std=c++17 -Wall -Wextra -O2 main.cpp decoder.cpp -o decoder
